#!/bin/sh

# Wrapper for custom DDEV php command.
# Includes absolute path translation from host to container.

REMOTE_PATH='/var/www/html/'
LOCAL_PATH="$PWD/"

for param; do
  if [[ "$param" == *"$LOCAL_PATH"* ]]; then
    param=${param//$LOCAL_PATH/$REMOTE_PATH}
  fi

  newparams+=("$param")
done

ddev . php ${newparams[@]}
