#!/bin/sh

# Wrapper for custom DDEV phpcs command.
# Includes absolute path translation from host to container.
# Necessary because PHP Sniffer & Beautifier extension needs to call a
#   batch file. See VSCode's settings.json file. Example setting:
# "phpsab.executablePathCS": "/Users/michael/sites/pmd-2023-winter/pmd/ddev-phpcs",
# Works with PHP Sniffer & Beautifier extension (valeryanm.vscode-phpsab).
# Assistance with parameter handling from https://github.com/ikappas/vscode-phpcs/issues/173

REMOTE_PATH='/var/www/html/'
LOCAL_PATH="$PWD/"

for param; do
  if [[ "$param" == *"$LOCAL_PATH"* ]]; then
    param=${param//$LOCAL_PATH/$REMOTE_PATH}
  fi

  newparams+=("$param")
done

ddev . phpcs ${newparams[@]}
